# Lista de ativos populares para o Screener / Exportação
# Contém principais ações do IBOVESPA e do S&P 500

TICKERS_IBOVESPA = [
    "RRRP3.SA", "ALOS3.SA", "ALPA3.SA", "ABEV3.SA", "ARZZ3.SA", "ASAI3.SA", "AZUL4.SA", "B3SA3.SA", "BBSE3.SA", "BBDC3.SA",
    "BBDC4.SA", "BRAP4.SA", "BBAS3.SA", "BRKM5.SA", "BRFS3.SA", "BPAC11.SA", "CRFB3.SA", "CCRO3.SA", "CMIG4.SA", "CIEL3.SA",
    "COGN3.SA", "CPLE6.SA", "CSAN3.SA", "CPFE6.SA", "CMIN3.SA", "CVCB4.SA", "CYRE3.SA", "DXCO3.SA", "ELET3.SA", "ELET6.SA",
    "EMBR3.SA", "ENGI11.SA", "ENEV11.SA", "EGIE3.SA", "EQTL3.SA", "EZTC3.SA", "FLRY3.SA", "GGBR4.SA", "GOAU4.SA", "NTCO3.SA",
    "SOMA3.SA", "HAPV3.SA", "HYPE3.SA", "IGTI11.SA", "IRBR3.SA", "ITSA4.SA", "ITUB4.SA", "JBSS3.SA", "KLBN11.SA", "RENT3.SA",
    "LREN3.SA", "LWSA3.SA", "MGLU3.SA", "MRFG3.SA", "CASH3.SA", "BEEF3.SA", "MRVE3.SA", "MULT3.SA", "PCAR3.SA", "PETR3.SA",
    "PETR4.SA", "PRIO3.SA", "PETZ3.SA", "RADL3.SA", "RAIZ4.SA", "RDOR3.SA", "RAIL3.SA", "SBSP3.SA", "SANB11.SA", "SMTO3.SA",
    "CSNA3.SA", "SLCE3.SA", "SUZB3.SA", "TAEE11.SA", "VIVT11.SA", "TIMS3.SA", "TOTS3.SA", "UGPA3.SA", "USIM5.SA", "VALE3.SA",
    "VIIA3.SA", "VBBR3.SA", "WEGE3.SA", "YDUQ3.SA"
]

TICKERS_SP500_TOP = [
    "AAPL", "MSFT", "AMZN", "NVDA", "GOOGL", "META", "TSLA", "BRK-B", "UNH", "JNJ", "JPM", "V", "PG", "XOM", "MA", "HD",
    "AVGO", "CVX", "LLY", "MRK", "PEP", "COST", "ABBV", "KO", "ADBE", "WMT", "MCD", "CSCO", "CRM", "BAC", "TMO", "PFE",
    "ACN", "CMCSA", "NFLX", "LIN", "AMD", "DIS", "DHR", "ABT", "TXN", "WFC", "INTC", "NKE", "PM", "VZ", "NEE", "INTU",
    "QCOM", "COP"
]

ALL_SCREENER_TICKERS = TICKERS_IBOVESPA + TICKERS_SP500_TOP
